import { extractParams } from '@/app-utils/extract-params';
import { ClientProviders } from '@/app/client-providers';
import { authOptions } from '@/auth';
import { redirect } from '@/i18n/navigation';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { headers } from 'next/headers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const PUBLIC_PREFIXES = ['/auth/sign-in'];
function isPublic(pathname: string) {
  return PUBLIC_PREFIXES.some((prefix) => pathname.includes(prefix));
}

export default async function RootLayout({ children, params }: LayoutProps<'/[locale]'>) {
  const { locale } = await extractParams(params);
  const messages = await getMessages({ locale });

  const session = await getServerSession(authOptions);
  if (!session) {
    const headersList = await headers();
    const pathname = headersList.get('x-pathname') ?? '/';
    if (!isPublic(pathname)) {
      redirect({ href: `/auth/sign-in?callbackUrl=${encodeURIComponent(pathname)}`, locale });
    }
  }

  return (
    <html
      lang={locale}
      className="h-full antialiased"
      dir={locale.startsWith('ar') ? 'rtl' : 'ltr'}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ClientProviders>{children}</ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
